[package]
name = "em_z80"
version = "0.1.0"
edition = "2021"
authors = ["Dan Shepherd"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.em_z80_lib]
path = "src/lib"