
import "../../fonts/Menlo.ttc";

import { Button, ListView, HorizontalBox, ScrollView, LineEdit, ComboBox , CheckBox} from "std-widgets.slint";

component DisplayView inherits Rectangle {
    width: 62.5%;
    height: self.width * (9.0/16.0);
}

component MemoryView inherits Rectangle {
    in property <[string]> data;
    out property <string> addr_str;
    in property <int> scroll_row;
    callback scroll_to_addr(string);
    width: 62.5%;
    vertical-stretch: 1;
    background: #323232;
    VerticalLayout {
        padding: 2px;
        HorizontalBox {
            Text {
                font-size: 11pt;
                text: "Memory";
            }
            LineEdit {
                width: 60px;
                placeholder-text: "HEX";
                edited(val) => {
                    root.addr_str = val;
                }
                accepted(val) => {
                    root.addr_str = val;
                    root.scroll_to_addr(root.addr_str);
                    i-memory-list.viewport-x = 0;
                    i-memory-list.viewport-y = -(root.scroll_row)*30px;
                }
            }
            Button {
                width: 60px;
                text: "Goto";
                enabled: { (root.addr_str != "") };
                clicked => {
                    root.scroll_to_addr(root.addr_str);
                    i-memory-list.viewport-x = 0;
                    i-memory-list.viewport-y = -(root.scroll_row)*30px;
                }
            }
        }
        Rectangle {
            background: #1C1C1C;
            width: 100%;
            vertical-stretch: 1;
            i-memory-list := ListView {
                for txt in data
                : Rectangle {
                    height: 30px;
                    width: 630px;
                    Text {
                        x: 0;
                        text: txt;
                        font-size: 11pt;
                    }
                }
            }
        }
    }
}

component RegisterView inherits Rectangle {
    in property <[string]> data;
    in property <[string]> status_flag_names;
    in property <[bool]> status_flag_states;
    callback set_register(string, string);
    callback update_status_flag(string, bool);
    out property <string> reg_str;
    out property <string> val_str;
    width: 37.5%;
    height: 50%;
    background: #323232;
    VerticalLayout {
        padding:2px;
        HorizontalBox {
            Text {
                font-size: 11pt;
                text: "Registers";
            }
            ComboBox {
                width: 80px;
                model: ["", "AF", "AF'", "BC", "BC'", "DE", "DE'", "HL", "HL'", "IX", "IY", "SP", "PC", "IR", "WZ"];
                current-value: "";
                selected(reg) => {
                    root.reg_str = reg;
                }
            }
            LineEdit {
                width: 60px;
                placeholder-text: "HEX";
                enabled: {root.reg_str != ""};
                edited(val) => {
                    root.val_str = val;
                }
                accepted(val) => {
                    root.val_str = val;
                    root.set_register(root.reg_str, root.val_str);
                }
            }
            Button {
                width: 60px;
                text: "Set";
                enabled: { (root.reg_str != "") && (root.val_str != "") };
                clicked => {
                    root.set_register(root.reg_str, root.val_str);
                }
            }
        }
        Rectangle {
            background: #1C1C1C;
            width: 100%;
            vertical-stretch: 1;
            HorizontalLayout {
                ListView {
                    horizontal-stretch: 1;       
                    for txt in data
                    : Rectangle {
                        height: 30px;
                        width: parent.width;
                        Text {
                            x: 0;
                            text: txt;
                            font-size: 11pt;
                        }
                    }
                }
                Rectangle {
                    background: #323232;
                    width: 100px;
                    vertical-stretch: 1;
                    VerticalLayout {
                        padding-left:10px;
                        padding-top: 10px;
                        padding-bottom: 10px;
                        for i in status-flag-states.length
                        : CheckBox {
                            checked: status-flag-states[i];
                            text: status-flag-names[i];
                            toggled => {
                                update-status-flag(self.text, self.checked);
                            }
                        }
                    }
                }
            }
        }
    }
}

component DisassemblyView inherits Rectangle {
    in property <[string]> data;
    in-out property <bool> is_running;
    callback step;
    callback start_stop;
    width: 37.5%;
    background: #323232;
    VerticalLayout {
        padding:2px;
        HorizontalBox {
            Text {
                font-size: 11pt;
                text: "Disassembly";
            }
            Button {
                width: 60px;
                text : "Step";
                enabled: !is_running; 
                clicked => {
                    root.step();
                }
            }
            Button {
                width: 60px;
                text: is_running ? "Stop" : "Run";
                clicked => {
                    root.start_stop();
                }
            }
        }
        Rectangle {
            background: #1C1C1C;
            width: 100%;
            vertical-stretch: 1;
            ListView {
                width: 100%;       
                for txt in data
                : Rectangle {
                    height: 30px;
                    background: {(txt == data[0]) ? #68cdff44 : #1C1C1C};
                    width: parent.width;
                    Text {
                        x: 0;
                        text: txt;
                        font-size: 11pt;
                    }
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    in property <[string]> memory_view_data;
    in property <[string]> register_view_data;
    in property <[bool]> status_view_data;
    in property <[string]> disassembly_view_data;
    in-out property <bool> is_running;
    in property <int> memory_scroll_row;
    callback step;
    callback start_stop;
    callback set_register(string, string);
    callback update_status_flag(string, bool);
    callback memory_scroll_to_addr(string);
    default-font-family: "Menlo";
    preferred-width: 1024px;
    min-width: 880px;
    preferred-height: 576px;
    min-height: 480px;
    title: "Z80 Emulator/Disassembler";
    HorizontalLayout {
        VerticalLayout {
            DisplayView {}
            MemoryView  {
                data: memory_view_data;
                scroll_row: memory_scroll_row;
                scroll_to_addr(addr) => {
                    root.memory_scroll_to_addr(addr);
                }
            }
        }
        VerticalLayout {
            RegisterView {
                data: register_view_data;
                status-flag-names: ["C","N","P/V","H","Z","S"];
                status-flag-states: status_view_data;
                set_register(reg, val) => {
                    root.set_register(reg, val);
                }
                update_status_flag(flag, val) => {
                    root.update_status_flag(flag, val);
                }
            }
            DisassemblyView {
                data: disassembly_view_data;
                is_running: is_running;
                step => {
                    root.step();
                }
                start_stop => {
                    root.start_stop();
                }
            }
        }
    }
}